### ISSUE TITLE
Head version number 1.0.0-dev breaks bundler

### ISSUE THREAD

**Issue by toph** [jhawthorn/clouddns#7]
I think the version number used in head (1.0.0-dev) may disagree with bundler.

I was interested in using the multiple TXT record support, so I set my Gemfile to point at `gem "clouddns", :git => "git@github.com:jhawthorn/clouddns.git"`.

However, when I run `bundle install`, I think the `-dev` trips things up.

```
Updating git@github.com:jhawthorn/clouddns.git
There was a ArgumentError while loading clouddns.gemspec: 
Malformed version number string 1.0.0-dev from
<OMITTED>/bundler/gems/clouddns-6cda1507aea1/clouddns.gemspec:16:in `block
in <main>'
```

Would you be up for a new version number?  I'm happy to submit a PR (since it's a small change) if you're busy!

**Comment by jhawthorn** [comment]
Switched the version to `1.0.0.pre`.
